using System.Text;
using YamlDotNet.Core;
using YamlDotNet.Core.Events;
using YamlDotNet.RepresentationModel;

namespace Logicality.GitHub.Actions.Workflow;

/// <summary>
/// Represents a GitHub Actions Workflow
/// </summary>
public class Workflow
{
    public const string Header = "# This was generated by tool. Edits will be overwritten.";

    private readonly string?                        _name;
    private readonly Dictionary<string, Permission> _permissions      = new();
    private readonly Dictionary<string, Job>        _jobs             = new();
    private          PermissionConfig               _permissionConfig = PermissionConfig.NotSpecified;
    private          string?                        _concurrencyGroup;
    private          bool                           _concurrencyCancelInProgress;
    private          IDictionary<string, string>    _env = new Dictionary<string, string>();
    private          WorkflowDefaults?              _defaults;


    /// <summary>
    /// Create a new instance of a Workflow
    /// </summary>
    /// <param name="name">The workflow name. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name</param>
    public Workflow(string? name = null)
    {
        _name = name;
        On    = new On(this);
    }

    /// <summary>
    /// Setup triggers for this workflow. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
    /// </summary>
    public On On { get; }

    /// <summary>
    /// Configure worklfow permissions. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    /// </summary>
    /// <param name="actions">Actions permission. Default is 'None'.</param>
    /// <param name="checks">Checks permission. Default is 'None'.</param>
    /// <param name="contents">Contents permission. Default is 'None'.</param>
    /// <param name="deployments">Deployments permission. Default is 'None'.</param>
    /// <param name="discussions">Discussion permission. Default is 'None'.</param>
    /// <param name="idToken">Id Token permission. Default is 'None'.</param>
    /// <param name="issues">Issues permission. Defualt is 'None'.</param>
    /// <param name="packages">Packages permission. Default is 'None'.</param>
    /// <param name="pages">Pages permission. Default is 'None'.</param>
    /// <param name="pullRequests">Pull requests permission. Default is 'None'.</param>
    /// <param name="repositoryProjects">Repository projects permission. Default is 'None'.</param>
    /// <param name="securityEvents">Security events permission. Default is 'None'.</param>
    /// <param name="statuses">Status permission. Default is 'None'.</param>
    /// <returns>The workflow.</returns>
    public Workflow Permissions(
        Permission actions            = Permission.None,
        Permission checks             = Permission.None,
        Permission contents           = Permission.None,
        Permission deployments        = Permission.None,
        Permission discussions        = Permission.None,
        Permission idToken            = Permission.None,
        Permission issues             = Permission.None,
        Permission packages           = Permission.None,
        Permission pages              = Permission.None,
        Permission pullRequests       = Permission.None,
        Permission repositoryProjects = Permission.None,
        Permission securityEvents     = Permission.None,
        Permission statuses           = Permission.None)
    {
        _permissions[PermissionKeys.Actions]            = actions;
        _permissions[PermissionKeys.Checks]             = checks;
        _permissions[PermissionKeys.Contents]           = contents;
        _permissions[PermissionKeys.Deployments]        = deployments;
        _permissions[PermissionKeys.Discussions]        = discussions;
        _permissions[PermissionKeys.IdToken]            = idToken;
        _permissions[PermissionKeys.Issues]             = issues;
        _permissions[PermissionKeys.Packages]           = packages;
        _permissions[PermissionKeys.Pages]              = pages;
        _permissions[PermissionKeys.PullRequests]       = pullRequests;
        _permissions[PermissionKeys.RepositoryProjects] = repositoryProjects;
        _permissions[PermissionKeys.SecurityEvents]     = securityEvents;
        _permissions[PermissionKeys.Statuses]           = statuses;

        _permissionConfig = PermissionConfig.Custom;

        return this;
    }

    /// <summary>
    /// Set workflow permissions to `read-all`. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    /// </summary>
    /// <returns>The workflow.</returns>
    public Workflow PermissionsReadAll()
    {
        _permissionConfig = PermissionConfig.ReadAll;
        return this;
    }

    /// <summary>
    /// Set workflow permissions to `write-all`. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    /// </summary>
    /// <returns>The workflow.</returns>
    public Workflow PermissionsWriteAll()
    {
        _permissionConfig = PermissionConfig.WriteAll;
        return this;
    }

    /// <summary>
    /// Set workflow concurrency. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
    /// </summary>
    /// <param name="group"></param>
    /// <param name="cancelInProgress"></param>
    /// <returns>The workflow.</returns>
    public Workflow Concurrency(string @group, bool cancelInProgress = false)
    {
        _concurrencyGroup            = @group;
        _concurrencyCancelInProgress = cancelInProgress;
        return this;
    }

    /// <summary>
    /// A map of environment variables that are available to the steps of all jobs in the workflow. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env
    /// </summary>
    /// <param name="map"></param>
    /// <returns>The workflow.</returns>
    public Workflow Env(params (string key, string value)[] map)
    {
        _env = map.ToDictionary();
        return this;
    }

    /// <summary>
    /// A set of default settings that will apply to all jobs in the workflow. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults
    /// </summary>
    /// <returns>The workflow.</returns>
    public WorkflowDefaults Defaults()
    {
        _defaults = new(this);
        return _defaults;
    }

    /// <summary>
    /// A map of default settings that will apply to all jobs in the workflow. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults
    /// </summary>
    /// <param name="map"></param>
    /// <returns>The workflow.</returns>
    public WorkflowDefaults Defaults(params (string key, string value)[] map)
    {
        _defaults = new(this, map.ToDictionary());
        return _defaults;
    }

    /// <summary>
    /// Add new Job to workflow.
    /// </summary>
    /// <param name="id">The unique identifier for the job.</param>
    /// <returns>The job.</returns>
    public Job Job(string id)
    {
        var job = new Job(id, this);
        _jobs.Add(id, job);
        return job;
    }

    /// <summary>
    /// Get the YAML representation of this workflow.
    /// </summary>
    /// <param name="sequenceStyle">The squence style for collections.</param>
    /// <returns>The YAML representation as a string.</returns>
    public string GetYaml(SequenceStyle sequenceStyle = SequenceStyle.Block) 
    {
        var rootNode     = new YamlMappingNode();
        if (!string.IsNullOrEmpty(_name))
        {
            rootNode.Add("name", new YamlScalarNode(_name));
        };
        var yamlDocument = new YamlDocument(rootNode);

        // Triggers
        On.Build(rootNode, sequenceStyle);

        // Permissions
        PermissionHelper.BuildPermissionsNode(rootNode, _permissionConfig, _permissions);

        // Concurrency
        if (!string.IsNullOrWhiteSpace(_concurrencyGroup))
        {
            var concurrencyMappingNode = new YamlMappingNode
            {
                { "group", _concurrencyGroup },
                { "cancel-in-progress", _concurrencyCancelInProgress.ToString().ToLower() }
            };
            rootNode.Add("concurrency", concurrencyMappingNode);
        }

        // Env
        if (_env.Any())
        {
            var envMappingNode = new YamlMappingNode();
            foreach (var env in _env)
            {
                envMappingNode.Add(env.Key, new YamlScalarNode(env.Value));
            }
            rootNode.Add("env", envMappingNode);
        }

        // Defaults
        _defaults?.Build(rootNode);

        // Jobs
        if (_jobs.Any())
        {
            var jobsNode = new YamlMappingNode();
            foreach (var job in _jobs)
            {
                job.Value.Build(jobsNode, sequenceStyle);
            }

            rootNode.Add("jobs", jobsNode);
        }

        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("# This was generated by tool. Edits will be overwritten.");
        stringBuilder.AppendLine();
        var stringWriter    = new StringWriter(stringBuilder);
        var yamlStream      = new YamlStream(yamlDocument);
        var emitterSettings = new EmitterSettings();
        var emitter         = new Emitter(stringWriter, emitterSettings);
        yamlStream.Save(emitter, false);

        // YamlDotnet inserts a "{}" for empty mapping. Just want empty string.
        var yaml = stringBuilder.ToString();
        yaml = yaml.Replace(" {}", string.Empty);

        // HACK For some reason yamldotnet adds a ".../r/n" to the end. This removes it.
        // Maybe I'm missing something...
        yaml = yaml.Remove(yaml.Length - 5, 5);

        return yaml;
    }

    /// <summary>
    /// Writes the YAML representation to a file.
    /// </summary>
    /// <param name="filePath">The file path.</param>
    /// <param name="sequenceStyle">The sequence style for YAML collections.</param>
    public void WriteYaml(string filePath, SequenceStyle sequenceStyle = SequenceStyle.Block)
    {
        var yaml = GetYaml(sequenceStyle);

        File.WriteAllText(filePath, yaml);
    }
}